<a href="https://colab.research.google.com/github/worthlessFella/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [16]:
# select values at multiple idx
x = np.random.randint(0, 1100, (5, 5))
print(x)
idx = [3, 4]
print(list(range(x.shape[0])))
print(x[list(range(x.shape[0])), [0, 1, 2, 3, 4]])

[[  87  217  836  536  166]
 [ 315  105  535  106  959]
 [ 797  488  254  304  871]
 [ 118  274  643  557  464]
 [ 852 1072  643  955  839]]
[0, 1, 2, 3, 4]
[ 87 105 254 557 839]


In [22]:
# select range along an axis in multidimensional array
x = np.random.randint(0, 1100, (5, 5))
print(x)
x[:, [2]:4]

[[ 559  909 1032  979  449]
 [ 354  592  185  655  513]
 [1045  157  740  560 1031]
 [ 839  892  273  435   91]
 [ 331 1000  945  858  889]]


TypeError: ignored